layout_spectrum: 0.6889046
typography_spectrum: 0.3514155
color:
  saturation: 0.4920868
  lightness: 0.7237006
  brandStrength: 0.2435869
  rhythmicContrast: 0.02393644
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Vincent Hankes
